FROM ubuntu
ENV https_proxy=dacian.cc:65534

RUN apt update && apt upgrade -y

RUN apt install wget -y



RUN wget https://github.com/google/cadvisor/releases/download/v0.45.0/cadvisor-v0.45.0-linux-amd64
RUN chmod +x cadvisor-v0.45.0-linux-amd64




ENTRYPOINT [ "/cadvisor-v0.45.0-linux-amd64", "-storage_driver=influxdb", "-storage_driver_host=dacian.cc:8086", "-storage_driver_db=cadvisor" , "-storage_driver_user=root", "-storage_driver_password=root"]