FROM ubuntu

RUN apt update && apt upgrade -y

RUN apt install ssh sudo -y
RUN systemctl enable ssh

# change user name here
ARG USERNAME=user2
# change user passwd here
ARG USERPASSWD=passwd

RUN useradd $USERNAME
RUN adduser $USERNAME sudo
RUN echo $USERNAME:$USERPASSWD | chpasswd
RUN echo root:$USERPASSWD | chpasswd


COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT [ "/entrypoint.sh" ]