
#! should be tested with `docker compose --compatibility config`

services:

  mysql:
    platform: linux/x86_64
    restart: always
    build: ./mysql
    ports:
      - 3306:3306
    volumes:
      # File    
      - type: bind
        source: ../dataset/mysql
        target: /var/lib/mysql
      # Config
      - type: bind
        source: ../configs/mysql.cnf
        target: /etc/my.cnf
        read_only: true

    container_name: mysql

  # redis:

  #   platform: linux/x86_64
  #   restart: always
  #   build: ./redis

  #   ports:
  #     - 6379:6379

  #   container_name: redis
