FROM ubuntu
RUN apt update && apt upgrade -y

RUN apt install wget -y

RUN wget https://github.com/google/cadvisor/releases/download/v0.47.0/cadvisor-v0.47.0-linux-amd64
RUN chmod +x cadvisor-v0.47.0-linux-amd64

ENTRYPOINT [ "/cadvisor-v0.47.0-linux-amd64"]
